"""ajout error_detail sur scraping_jobs

Revision ID: 0ecab67afc3b
Revises: f20cae59a4c4
Create Date: 2026-09-02 22:55:54.827149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecab67afc3b'
down_revision: Union[str, Sequence[str], None] = 'f20cae59a4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_jobs', sa.Column('error_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_jobs', 'error_detail')
    # ### end Alembic commands ###
